In [ ]:
import pandas as pd 
import numpy as np

: 

In [ ]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [ ]:
batch_size=1

Dataset

In [ ]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [ ]:
dataset=pd.DataFrame(data)

In [ ]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [ ]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [ ]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [ ]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [ ]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [ ]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [ ]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [ ]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [ ]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

**The 100 epocs**

In [ ]:
Epoc = 100
for x in range(Epoc):
  print( 'Epoc number:', x ,'\n')
  weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
  weight_2=array([[.5],[.1]])
  weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
  weight_2=uniform(-1,1,(2,1))
  output_1=X_norm[0:batch_size]@weight_1
  output_1
  act_output=sigmoid(output_1).numpy()
  act_output
  pred_output=act_output@weight_2
  pred_output=np.reshape(pred_output,(1,-1))
  pred_output
  y_true=y_norm[0][0:batch_size]
  y_pred=pred_output
  mse(y_true,y_pred).numpy()

  #Back Propagation

  y1 = y_true[0]
  y2 = y_pred
  output=y1-y2
  output2 = y2*(1-y2)
  error_k = output * output2

  #Error of hidden Layers 𝑬𝒓𝒓𝒐𝒓(𝒋) = 𝒆𝒓𝒓𝒐𝒓 𝒂𝒕 𝒌 ∗ 𝒘𝒆𝒊𝒈𝒉𝒕 𝒐𝒇 𝒘𝒋𝒌 ∗ 𝒇’(𝒙𝒋)
  error_j = error_k * weight_2[0][0] * (act_output[0][0] * (1 - act_output[0][0]))
  error_i = error_k * weight_2[1][0] * (act_output[0][1] * (1 - act_output[0][1]))

  #Delta rule: 𝑊𝑛𝑒𝑤 = 𝑊𝑐𝑢𝑟𝑟𝑒𝑛𝑡 + Δ𝑊𝑐𝑢𝑟𝑟𝑒𝑛t
  n = uniform(0,1)
  w_new_j = weight_2[0][0] + (n * error_k * y_pred)
  w_new_j = np.reshape(array(w_new_i),(1,1))
  w_new_i = weight_2[1][0] + (n * error_k * y_pred)
  w_new_i = np.reshape(array(w_new_i),(1,1))
  weight_2_update = np.concatenate((w_new_j, w_new_i))
  print('weight_2_update\n')
  print(weight_2_update, '\n')

  #Calculating weights for the first layer
  weight_1_update = weight_1[:,0].reshape(-1,1) + (n * error_j * output_1[0][0])
  weight_1_update_cont = weight_1[:,1].reshape(-1,1) + (n * error_i * output_1[0][1])
  weight_1_update = np.concatenate((weight_1_update, weight_1_update_cont), axis=1)
  print('Weight_1_update\n')
  print(weight_1_update, '\n')

  #Uisng the updated weights
  output_1=X_norm[0:batch_size]@weight_1_update
  output_1
  act_output=sigmoid(output_1).numpy()
  act_output
  pred_output=act_output@weight_2_update
  pred_output=np.reshape(pred_output,(1,-1))
  print('Predicted output:\n')
  print(pred_output)
  y_true=y_norm[0][0:batch_size]
  print('Expected output:\n')
  print(y_true)
  y_pred=pred_output
  mse(y_true,y_pred).numpy()







Epoc number: 0 

weight_2_update

[[ 0.16335414]
 [-0.11490712]] 

Weight_1_update

[[0.50008181 0.93084318]
 [0.86441363 0.77603478]
 [0.03078744 0.06074432]] 

Predicted output:

[[0.03101672]]
Expected output:

[0.28571429]
Epoc number: 1 

weight_2_update

[[-0.11490712]
 [-0.99617316]] 

Weight_1_update

[[-0.57751422 -0.30746419]
 [ 0.59137382 -0.41951121]
 [-0.77750908 -0.86317448]] 

Predicted output:

[[-0.23910656]]
Expected output:

[0.28571429]
Epoc number: 2 

weight_2_update

[[-0.99617316]
 [ 0.15863763]] 

Weight_1_update

[[-0.28721242 -0.51226187]
 [-0.87587377 -0.16363101]
 [-0.54656114  0.78816946]] 

Predicted output:

[[-0.10092499]]
Expected output:

[0.28571429]
Epoc number: 3 

weight_2_update

[[ 0.15863763]
 [-0.54556012]] 

Weight_1_update

[[ 0.75409548 -0.05522147]
 [-0.10807494  0.48149905]
 [-0.8074738   0.28887908]] 

Predicted output:

[[-0.2952349]]
Expected output:

[0.28571429]
Epoc number: 4 

weight_2_update

[[-0.54556012]
 [-0.49010804]] 

Weigh

Trials of the first epoc. 

In [ ]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [ ]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [ ]:
weight_1[:,0]

array([-0.78241051,  0.97850948,  0.61171609])

In [ ]:
weight_2[0][0]


-0.05700184421194976

In [ ]:
X_norm[0:batch_size]

array([[0.6, 0.8, 1. ]])

In [ ]:
output_1=X_norm[0:batch_size]@weight_1
output_1

array([[0.92507737, 0.00661548]])

In [ ]:
act_output=sigmoid(output_1).numpy()
act_output

array([[0.17213741, 0.53081362]])

In [ ]:
pred_output=act_output@weight_2
pred_output=np.reshape(pred_output,(1,-1))
pred_output

array([[-0.22372245]])

Mean Squared Error

In [ ]:
y_true=y_norm[0][0:batch_size]
y_pred=pred_output

In [ ]:
y_pred

array([[-0.22372245]])

In [ ]:
y_true

array([0.28571429])

In [ ]:
mse(y_true,y_pred).numpy()

array([0.25952579])

Back Propagation

In [ ]:
y1 = y_true[0]
y1

0.2857142857142857

In [ ]:
y2 = y_pred
y2

array([[-0.22372245]])

In [ ]:
output=y1-y2
output

array([[0.50943673]])

Error Computation

In [ ]:
output2 = y2*(1-y2)
output2

array([[-0.27377418]])

In [ ]:
error_k = output * output2
error_k

array([[-0.13947062]])

Error of hidden Layers
𝑬𝒓𝒓𝒐𝒓(𝒋) = 𝒆𝒓𝒓𝒐𝒓 𝒂𝒕 𝒌 ∗ 𝒘𝒆𝒊𝒈𝒉𝒕 𝒐𝒇 𝒘𝒋𝒌 ∗ 𝒇’(𝒙𝒋)

In [ ]:
error_j = error_k * weight_2[0][0] * (act_output[0][0] * (1 - act_output[0][0]))
error_j

array([[-0.00018749]])

In [ ]:
error_i = error_k * weight_2[1][0] * (act_output[0][1] * (1 - act_output[0][1]))
error_i

array([[0.00012172]])

Delta rule: 𝑊𝑛𝑒𝑤 = 𝑊𝑐𝑢𝑟𝑟𝑒𝑛𝑡 + Δ𝑊𝑐𝑢𝑟𝑟𝑒𝑛t



In [ ]:
n = uniform(0,1)
n

0.27463246267170593

In [ ]:
w_new_j = weight_2[0][0] + (n * error_k * y_pred)
w_new_j = np.reshape(array(w_new_i),(1,1))
w_new_j

array([[0.16335414]])

In [ ]:
w_new_i = weight_2[1][0] + (n * error_k * y_pred)
w_new_i = np.reshape(array(w_new_i),(1,1))
w_new_i

array([[-0.35603436]])

In [ ]:
weight_2_update = np.concatenate((w_new_j, w_new_i))
print('weight_2_update\n')
weight_2_update

weight_2_update



array([[-0.20454047],
       [-0.35603436]])

In [ ]:
weight_1

array([[-0.78241051,  0.80730479],
       [ 0.97850948,  0.27413821],
       [ 0.61171609, -0.69707797]])

In [ ]:
output_1

array([[0.92507737, 0.00661548]])

In [ ]:
output_1[0][1]

0.0066154768868529334

In [ ]:
 weight_1

array([[-0.78241051,  0.80730479],
       [ 0.97850948,  0.27413821],
       [ 0.61171609, -0.69707797]])

In [ ]:
weight_1[:,0]

array([-0.78241051,  0.97850948,  0.61171609])

In [ ]:
weight_1[:,0].reshape(-1,1)

array([[-0.78241051],
       [ 0.97850948],
       [ 0.61171609]])

Calculating weights for the first layer

In [ ]:
weight_1_update = weight_1[:,0].reshape(-1,1) + (n * error_j * output_1[0][0])
weight_1_update_cont = weight_1[:,1].reshape(-1,1) + (n * error_i * output_1[0][1])
weight_1_update = np.concatenate((weight_1_update, weight_1_update_cont), axis=1)
print('Weight_1_update\n')
weight_1_update

Weight_1_update



array([[-0.78296347,  0.8072795 ],
       [ 0.97795652,  0.27411292],
       [ 0.61116313, -0.69710326]])